### ISSUE TITLE
FHA (ARP4761) analysis produces empty reports on ARP4761 bscu examples.

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-plugins#88]
I loaded the ARP2761 example models.  The bscu.basic and bscu.generic
models have hazards declared, so I tried running the FHA (ARP4761)
analysis.  I got blank reports.  What tools can I run on what system
implementations in that example?  I couldn't find any documentation on
what tools can be applied to the examples.

**Comment by reteprelief** [comment]
The issue is that the example used EMV2::Hazards properties while the ARP4761 report looks for ARP4761::Hazards.
I updated the example model to use ARP4761 properties. That uncovered a bug in the ARP4761 property set that it did not have the Hazardous label. It is been added in through a separate issue report and will show in the next Testing (nightly) build.
